staging:
  deploy_to: "/var/www/consul"
  ssh_port: 21
  server: <%= ENV['SERVER_IP'] %>
  user: <%= ENV['MAIN_USER'] %>
  full_app_name: <%= ENV['FULL_APP_NAME'] %>
  server_name: <%= ENV['MAIN_URL'] %>
  db_server: <%= ENV['POSTGRES_SERVER'] %>

preproduction:
  deploy_to: "/var/www/consul"
  ssh_port: 2222
  server1: <%= ENV['SERVER_IP'] %>
  server2: <%= ENV['SERVER_IP'] %>
  user: <%= ENV['MAIN_USER'] %>
  full_app_name: consul
  db_server: <%= ENV['POSTGRES_SERVER'] %>

production:
  deploy_to: "/var/www/consul"
  ssh_port: 2222
  server: <%= ENV['SERVER_IP'] %>
  user: <%= ENV['MAIN_USER'] %>
  full_app_name: consul

