default: &default
  secret_key_base: "56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4"

development:
  <<: *default

test:
  <<: *default

staging:
  server_name: ""
  <<: *default

production: &production
  secret_key_base: "817232feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4"

  census_api_token:
    host: ""
    path: "/identity/connect/token"
    params:
      username: ""
      password: ""
      grant_type: "password"
      scope: ""
      client_id: ""
      client_secret: ""
  census_api_end_point: ""

  sms_sender_phone: "123456789"
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

  http_basic_username: ""
  http_basic_password: ""

  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""

  rollbar_server_token: ""
  server_name: ""

preproduction:
  server_name: ""
  <<: *production
